# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2016-12-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('number', models.SmallIntegerField(default=1)),
                ('curent_class', models.CharField(max_length=10)),
                ('systems_networks', models.CharField(max_length=2)),
                ('overall_grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('titles', models.CharField(max_length=100)),
                ('systems_networks', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('systems_networks', models.CharField(max_length=2)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis.Teacher')),
            ],
        ),
    ]
