# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-01-20 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=200)),
                ('reviewer_titles', models.CharField(max_length=200)),
                ('place_of_work', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=200)),
                ('titles', models.CharField(max_length=200)),
                ('place_of_work', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thesis_description', models.TextField()),
                ('type_thesis', models.CharField(max_length=200)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Reviewer'),
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_thesis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Thesis'),
        ),
    ]
