# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-01-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20170120_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='system_programming',
            field=models.BooleanField(default=False),
        ),
    ]
