# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-01-29 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_teacher_system_programming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='type_thesis',
        ),
        migrations.AddField(
            model_name='thesis',
            name='hardware',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thesis',
            name='software',
            field=models.BooleanField(default=True),
        ),
    ]
