# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-01-30 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20170129_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archive_name', models.CharField(max_length=60)),
                ('students_database', models.FileField(upload_to='archives')),
            ],
        ),
    ]
