# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20170204_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=300)),
                ('category', models.CharField(default='System Programming', max_length=60)),
                ('place', models.CharField(default='none', max_length=30)),
                ('time', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManagmentAndReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=300)),
                ('category', models.CharField(default='System Programming', max_length=60)),
                ('titles', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='class_char',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='has_assignment',
            new_name='handed_assignment_over',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='has_document',
            new_name='handed_document_over',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='thesis',
            old_name='thesis_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='assigned_teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='has_commission',
        ),
        migrations.RemoveField(
            model_name='student',
            name='has_reviewer',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='system_programming',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='software',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='thesis_description',
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(default='System Programming', max_length=60),
        ),
        migrations.AddField(
            model_name='student',
            name='did_graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='study_period',
            field=models.CharField(default='2017-2018', max_length=30),
        ),
        migrations.AddField(
            model_name='thesis',
            name='category',
            field=models.CharField(default='System Programming', max_length=60),
        ),
        migrations.AddField(
            model_name='thesis',
            name='name',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='assigned_reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='admin_panel.ManagmentAndReview'),
        ),
        migrations.DeleteModel(
            name='Reviewer',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='commission',
            name='chairman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.ManagmentAndReview'),
        ),
        migrations.AddField(
            model_name='commission',
            name='commissioners',
            field=models.ManyToManyField(related_name='commissioners', to='admin_panel.ManagmentAndReview'),
        ),
        migrations.AddField(
            model_name='commission',
            name='students',
            field=models.ManyToManyField(related_name='students', to='admin_panel.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='admin_panel.ManagmentAndReview'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.ManagmentAndReview'),
        ),
    ]
