# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-09 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_auto_20170207_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='students',
            field=models.ManyToManyField(related_name='students_in_commission', to='admin_panel.Student'),
        ),
    ]
