# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_auto_20170209_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='is_prearranged',
            field=models.BooleanField(default=True),
        ),
    ]
