# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-11 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_thesis_is_prearranged'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='handed_documentation_over',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='student',
            name='assigned_thesis',
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_thesis',
            field=models.ManyToManyField(related_name='thesis_topic', to='admin_panel.Thesis'),
        ),
    ]
