# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_auto_20170211_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=2),
        ),
    ]
