# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_remove_student_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='smth',
            field=models.CharField(default='hello', max_length=1),
        ),
    ]
