# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-11 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_student_smth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='smth',
        ),
        migrations.AddField(
            model_name='student',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
