# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-11 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_auto_20170211_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='place',
            field=models.CharField(default='1st', max_length=5),
        ),
    ]
