# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-11 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_thesis_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='assigned_thesis',
            new_name='current_thesis',
        ),
    ]
