# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-11 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_auto_20170211_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='is_prearranged',
        ),
        migrations.AddField(
            model_name='student',
            name='has_prearranged_thesis',
            field=models.BooleanField(default=True),
        ),
    ]
