# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_auto_20170212_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='place',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AlterField(
            model_name='commission',
            name='time',
            field=models.CharField(default='none', max_length=60, null=True),
        ),
    ]
