# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_auto_20170220_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='when',
            field=models.CharField(default='never', max_length=30),
        ),
        migrations.AlterField(
            model_name='commission',
            name='time',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
