# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-23 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20170220_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagmentAndReview',
            new_name='ManagementAndReview',
        ),
        migrations.AlterField(
            model_name='commission',
            name='place',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
