# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_auto_20170223_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='when',
        ),
        migrations.AddField(
            model_name='commission',
            name='date',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AlterField(
            model_name='commission',
            name='time',
            field=models.CharField(default='never', max_length=30),
        ),
    ]
