# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-25 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_auto_20170225_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='admin_panel.Commission'),
        ),
    ]
