# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-26 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_auto_20170225_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(default='2017-2018', max_length=15)),
            ],
        ),
    ]
