# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-27 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_currentperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentperiod',
            name='is_current_period',
            field=models.BooleanField(default=False),
        ),
    ]
