# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-27 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_currentperiod_is_current_period'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentPeriod',
            new_name='Period',
        ),
    ]
