# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161103114236 on 2017-02-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_auto_20170227_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='period_given',
            field=models.CharField(default='2017-2018', max_length=15),
        ),
    ]
