from django.conf.urls import url
from . import views
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^$', views.admin_homepage, name='admin_homepage'),
    url(r'^new_year/$', views.new_year, name='new_year'),
    url(r'^man_years/$', views.man_years, name='man_years'),
    url(r'^upload_students/$', views.upload_students, name='upload_students'),
    url(r'^upload_supervisors/$', views.upload_supervisors, name='upload_supervisors'),
    url(r'^upload_thesis/$', views.upload_thesis, name='upload_thesis'),
    url(r'^listing/$', views.listing, name='listing'),
    url(r'^supervisor_handler/$', views.supervisor_handler, name='supervisor_handler'),
    url(r'^supervisor_handler/redirection/$', RedirectView.as_view(url=reverse_lazy('upload_supervisors')), name='supervisor_handler/redirection'),
    url(r'^student_handler/$', views.student_handler, name='student_handler'),
    url(r'^student_handler/redirection/$', RedirectView.as_view(url=reverse_lazy('upload_students')), name='student_handler/redirection'),
    url(r'^thesis_handler/$', views.thesis_handler, name='thesis_handler'),
    url(r'^thesis_handler/redirection/$', RedirectView.as_view(url=reverse_lazy('upload_thesis')), name='thesis_handler/redirection'),
    url(r'^file_handler/$', views.file_handler, name='file_handler'),
    url(r'^file_handler/redirection/$', RedirectView.as_view(url=reverse_lazy('upload_students')), name='file_handler/redirection'),
    url(r'^standard_handler/$', views.standard_handler, name='standard_handler'),
    url(r'^standard_handler/redirection/$', RedirectView.as_view(url=reverse_lazy('admin_homepage')), name='standard_handler/redirection'),
    url(r'^prearranged_handler/$', views.prearranged_handler, name='prearranged_handler'),
    url(r'^prearranged_handler/redirection/$', RedirectView.as_view(url=reverse_lazy('admin_homepage')), name='prearranged_handler/redirection'),
    url(r'^new_commission_handler/$', views.new_commission_handler, name='new_commission_handler'),
    url(r'^new_commission_handler/redirection/$', RedirectView.as_view(url=reverse_lazy('admin_homepage')), name='new_commission_handler/redirection'),
    url(r'^existing_commission_handler/$', views.existing_commission_handler, name='existing_commission_handler'),
    url(r'^existing_commission_handler/redirection/$', RedirectView.as_view(url=reverse_lazy('admin_homepage')), name='existing_commission_handler/redirection'),
    url(r'^reviewer_connect/$', views.reviewer_connect, name='reviewer_connect'),
    url(r'^reviewer_connect/redirection/$', RedirectView.as_view(url=reverse_lazy('admin_homepage')), name='reviewer_connect/redirection'),
    url(r'^graduate/$', views.graduate, name='graduate'),
    url(r'^graduate/redirection/$', RedirectView.as_view(url=reverse_lazy('admin_homepage')), name='graduate/redirection'),
    url(r'^period_change/$', views.period_change, name='period_change'),
    url(r'^period_change/redirection/$', RedirectView.as_view(url=reverse_lazy('admin_homepage')), name='period_change/redirection'),
    url(r'^supervisor_file_handler/$', views.supervisor_file_handler, name='supervisor_file_handler'),
    url(r'^supervisor_file_handler/redirection/$', RedirectView.as_view(url=reverse_lazy('upload_supervisors')), name='supervisor_file_handler/redirection'),
    url(r'^thesis_file_handler/$', views.thesis_file_handler, name='thesis_file_handler'),
    url(r'^thesis_file_handler/redirection/$', RedirectView.as_view(url=reverse_lazy('upload_thesis')), name='thesis_file_handler/redirection'),

    url(r'^(?P<student_id>[0-9]+)/assign_document/$', views.assign_document, name='assign_document'),
    url(r'^(?P<student_id>[0-9]+)/update_student/$', views.update_student, name='update_student'),
    url(r'^(?P<student_id>[0-9]+)/update_student/redirection/$', RedirectView.as_view(url=reverse_lazy('listing')), name='update_student/redirection'),
    url(r'^(?P<man_rev_id>[0-9]+)/update_man_review$', views.update_man_review, name='update_man_review'),
    url(r'^(?P<man_rev_id>[0-9]+)/update_man_review/redirection/$', RedirectView.as_view(url=reverse_lazy('listing')), name='update_man_review/redirection'),
    url(r'^(?P<thesis_id>[0-9]+)/update_thesis$', views.update_thesis, name='update_thesis'),
    url(r'^(?P<thesis_id>[0-9]+)/update_thesis/redirection/$', RedirectView.as_view(url=reverse_lazy('listing')), name='update_thesis/redirection'),
    url(r'^(?P<commission_id>[0-9]+)/update_commission$', views.update_commission, name='update_commission'),
    url(r'^(?P<commission_id>[0-9]+)/update_commission/redirection/$', RedirectView.as_view(url=reverse_lazy('listing')), name='update_commission/redirection'),
    url(r'^(?P<student_id>[0-9]+)/standard_thesis/$', views.standard_thesis, name='standard_thesis'),
    url(r'^(?P<student_id>[0-9]+)/handed_assignment_over/$', views.handed_assignment_over, name='handed_assignment_over'),
    url(r'^(?P<student_id>[0-9]+)/handed_documentation_over/$', views.handed_documentation_over, name='handed_documentation_over'),
    url(r'^(?P<student_id>[0-9]+)/redirection/$', RedirectView.as_view(url=reverse_lazy('admin_homepage')), name='redirection'),
    url(r'^(?P<thesis_id>[0-9]+)/finilize/$', views.finilize, name='finilize'),
    url(r'^(?P<student_id>[0-9]+)/finilize/redirection/$', RedirectView.as_view(url=reverse_lazy('admin_homepage')), name='finilize/redirection'),
    url(r'^(?P<student_id>[0-9]+)/finilize/redirection/$', RedirectView.as_view(url=reverse_lazy('admin_homepage')), name='finilize/redirection'),
    url(r'^(?P<student_id>[0-9]+)/reviewer_assign/$', views.reviewer_assign, name='reviewer_assign'),
    url(r'^(?P<student_id>[0-9]+)/commission_assign/$', views.commission_assign, name='commission_assign'),
]
